# Generated by Django 4.1.7 on 2023-04-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paystuff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carddetails',
            name='cvv',
        ),
        migrations.AddField(
            model_name='carddetails',
            name='securityCode',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='expiryDate',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='number',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
