# Generated by Django 4.1.7 on 2023-04-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paystuff', '0002_remove_carddetails_cvv_carddetails_securitycode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='last_4_card_digits',
        ),
        migrations.AddField(
            model_name='payment',
            name='cardNumber',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='expiryDate',
            field=models.CharField(max_length=5),
        ),
    ]
