# Generated by Django 4.1.7 on 2023-05-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paystuff', '0004_delete_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='New', max_length=10),
        ),
    ]
