# Generated by Django 4.1.7 on 2023-05-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paystuff', '0005_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='dateCreated',
            field=models.DateTimeField(),
        ),
    ]
