# Generated by Django 4.1.7 on 2023-05-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paystuff', '0006_alter_transaction_datecreated'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='refundAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updateTime',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='carddetails',
            name='number',
            field=models.CharField(max_length=19, null=True),
        ),
    ]
