# Generated by Django 4.1.7 on 2023-05-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paystuff', '0007_transaction_refundamount_transaction_updatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='updateTime',
            field=models.DateTimeField(),
        ),
    ]
