# Generated by Django 4.1.7 on 2023-05-03 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paystuff', '0011_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cards',
            new_name='card_details',
        ),
    ]
