# Generated by Django 4.1.7 on 2023-05-05 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paystuff', '0012_rename_cards_user_card_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='callback_url',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='card_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='paystuff.carddetails'),
        ),
    ]
