# Generated by Django 4.1.7 on 2023-05-05 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paystuff', '0014_alter_transaction_card_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='card_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='paystuff.carddetails'),
        ),
    ]
