# Generated by Django 4.1.7 on 2023-05-05 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paystuff', '0015_alter_transaction_card_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='card_details',
        ),
        migrations.AddField(
            model_name='carddetails',
            name='user_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='paystuff.user'),
        ),
    ]
